language: python 
python: 
  - "3.6"

env:
  global:
    - OFFICIAL_REPO="slaclab/ease"
    - secure: "QNHJ6xXlJkCp3ZGoDZjFySIOIdV3MU3d1Rs2ZzduQjjRTrouDIM5sOcYG6yF3WXgD9+yi3KaiUWh/j8SwpwLgzWuj+8uoHSftxogjsJMqPc3P6lU1Q/jvEkdalt3cAR7Xk1VxPK7S66H69J2wNtxuWQ4yzkd/jbwxLorr2FhbtMfbz3MmLma+44JZS6efAPgHwyor2fEwcT2XcjXRzfhRCde4jT6sp8PJBWxHFtahqVuLaNW0PrymbyVMGJm8tBqpFQoy/Bnl/NGtoSlysRzq1ZrL52wSxyJn8GcLx6h0WX75Ow1DamwW5wvkBDsrNB/KoZvdzzyLovQIYqnEWMf/565NAZNioYBERnNkDxWNab9eksuk21M+blyJjH5J4C2NziGGclGiaulbSBFe7EK6Sef/W+cg6K/IIGFA2laEDx1ZtGFCyGooFF0ttvuoEerdJi6jCVWyXCAiqS5Cee6o3o1Z8TBEqCfD3RjQ1OeLMZS65h1UOiXYt3iBkWbhla512eSoN4+Aewn52iAu2vGm85kWQlj0N+OtYL5BrV9ZcixVvF1Enq3aecONwkGoQEHqNLopFMMxVA+pUBha0p+D80n7gI2xSe/fowpBR463uHiibhfuJkJ92VLS+34NfWRsiU/ugwBCcnLn7RSYIlwm7tbU00ZoFbqvbfXF0BI1U8=" 

sudo: false

git:
  depth: 5

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda
  - conda info -a
  # travis is currently experiencing a bug, the --quiet option appears to fix
  - conda env create -f environment.yml -n ease-env --quiet
  - source activate ease-env
  - cd ease/web_interface
  - curl -L -O https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - tar -vzxf geckodriver-v0.18.0-linux64.tar.gz
  - ./manage.py migrate
  - cd
  - pip install coverage codecov
  - pip install -r requirements.txt

script:
  - cd ease/web_interface
  - coverage run --source '.' ./manage.py test
  - cd
  - cd ease/alerts_engine
  - coverage run run_tests.py
  - cd
  - |
    if [[ $TRAVIS_REPO_SLUG == $OFFICIAL_REPO ]]; then
      set -e
      pip install doctr
      cd docs
      make html
      cd
      doctr deploy . --built-docs docs/_build/html --command "touch .nojekyll; git add .nojekyll"
    fi

after_success:
  - coverage combine ease/alerts_engine/.coverage ease/web_interface/.coverage
  - coverage report -m 
  - codecov
